# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elige Tu Presidente 2016 || Vagamos sentir nuestra voz
email: enzo-vezzaro@live.it
description: Las elecciones generales de la República Dominicana del 2016 se celebrarán el domingo 15 de mayo de forma simultánea en todo el territorio del país. Entra y vota por tu candidato.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://eligetupresidenterd.com" # the base hostname & protocol for your site
twitter_username: vezzaro_enzo
github_username:  EnzoVezzaro

# Build settings
markdown: kramdown
